name: scan-scorecard-security
on:
  pull_request:
    branches: [ "main" ]
  branch_protection_rule:

  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  INSIDE_REPO_PUSH: ${{ github.event_name == 'push' && github.repository == 'openvisualcloud/media-communications-mesh' }}

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  scorecard-analysis:
    name: "scorecard-analysis"
    runs-on: ubuntu-22.04
    if: |
      github.event_name == 'push' &&
      github.repository == 'openvisualcloud/media-communications-mesh' &&
      '${{ github.head_ref || github.ref_name }}' == 'main'
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read
    steps:
      - name: "scorecard: Harden Runner security"
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - name: "scorecard: Checkout code"
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          persist-credentials: false

      - name: "scorecard: Run analysis"
        uses: ossf/scorecard-action@dc50aa9510b46c811795eb24b2f1ba02a914e534 # v2.3.3
        with:
          results_file: "scorecard-scan-results-${{ github.event.pull_request.number || github.ref }}.sarif"
          results_format: sarif
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          publish_results: true

      - name: "scorecard: Upload results artifact"
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: "scorecard-scan-results-${{ github.event.pull_request.number || github.ref }}"
          path: "scorecard-scan-results-${{ github.event.pull_request.number || github.ref }}.sarif"
          retention-days: 5

      - name: "scorecard: Upload results to code-scanning"
        uses: github/codeql-action/upload-sarif@b611370bb5703a7efb587f9d136a52ea24c5c38c # v3.25.11
        with:
          sarif_file: "scorecard-scan-results-${{ github.event.pull_request.number || github.ref }}.sarif"

  dependency-review:
    name: "dependency-review"
    runs-on: ubuntu-22.04
    if: ${{ github.repository == 'openvisualcloud/media-communications-mesh' }}
    steps:
      - name: "dependency-review: Harden Runner security"
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - name: 'dependency-review: Checkout Repository'
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: 'dependency-review: Review dependencies'
        uses: actions/dependency-review-action@72eb03d02c7872a771aacd928f3123ac62ad6d3a # v4.3.3
